CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) UNIQUE NOT NULL,
  google_user_id VARCHAR(190) NULL,
  nombre_docente VARCHAR(190) NOT NULL,
  escuela VARCHAR(190) NOT NULL,
  nivel VARCHAR(50) NOT NULL,
  grado VARCHAR(50) NOT NULL,
  grupo VARCHAR(50) NULL,
  logo_url VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS memberships (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 0,
  plan VARCHAR(20) NOT NULL DEFAULT 'anual',
  expires_at DATE NULL,
  last_event VARCHAR(50) NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS templates (
  version VARCHAR(20) PRIMARY KEY,
  estado VARCHAR(10) NOT NULL DEFAULT 'activo',
  cuerpo MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nivel VARCHAR(50) NOT NULL,
  grado VARCHAR(50) NOT NULL,
  campo VARCHAR(120) NOT NULL,
  clave VARCHAR(50) NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  descripcion TEXT,
  estado VARCHAR(10) NOT NULL DEFAULT 'activo'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
